In [22]:
import cv2 as cv
import numpy as np


In [23]:
f = np.zeros((5,5), dtype = np.uint8)
f[2,2] = 1
w = np.asarray([[1,2,3],
              [4,5,6],
              [7,8,9]], dtype=np.uint8)

print("Correlation")
g = cv.filter2D(f, -1, w, borderType=cv.BORDER_CONSTANT)
print(g)
print('-------------')
print("Convolution")
w1 = cv.flip(w, -1)
h = cv.filter2D(f, -1, w1, borderType=cv.BORDER_CONSTANT)
print(h)

Correlation
[[0 0 0 0 0]
 [0 9 8 7 0]
 [0 6 5 4 0]
 [0 3 2 1 0]
 [0 0 0 0 0]]
-------------
Convolution
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [24]:
a = np.asarray([[1,6,11,16,21],
               [2,7,12,17,22],
               [3,8,13,18,23],
               [4,9,14,19,24],
               [5,10,15,20,25]], dtype=np.float32)
k  = np.ones((3,3), dtype=np.float32)
k = k/9

out = cv.filter2D(a,-1,k, borderType=cv.BORDER_CONSTANT )
print(out)

[[ 1.7777778  4.3333335  7.666667  11.000001   8.444445 ]
 [ 3.         7.0000005 12.000001  17.000002  13.       ]
 [ 3.6666667  8.        13.        18.        13.666667 ]
 [ 4.3333335  9.        14.        19.        14.333333 ]
 [ 3.1111112  6.333333   9.666666  13.         9.777778 ]]


In [25]:
b=np.asarray([[1,2,0,1,2],
              [2,3,1,1,2],
              [1,4,2,2,0],
              [3,2,3,3,0],
              [1,0,0,2,1]
              ], dtype=np.uint8)

w = np.asarray([[1,1,1],
              [1,1,2],
              [2,1,1]], dtype=np.uint8)

print("Correlation")
img = cv.filter2D(b, -1, w, borderType=cv.BORDER_CONSTANT)
print(img)

print("-------")
print("Convolution")
w1 = cv.flip(w, -1)
img1 = cv.filter2D(b, -1, w1, borderType=cv.BORDER_CONSTANT)
print(img1)

Correlation
[[10 11 12 10  7]
 [16 18 21 15 10]
 [19 26 25 17 11]
 [13 20 21 13 10]
 [ 6  9 12 10  6]]
-------
Convolution
[[ 8 10 10  7  7]
 [15 18 20 14  9]
 [18 23 26 18 10]
 [15 21 22 16 11]
 [ 8 13 13  9  8]]
